/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package SpareLinkPackage;

import java.awt.Component;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.time.LocalDate;
import java.time.LocalTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.Locale;
import javax.swing.JLabel;
import javax.swing.JPanel;
/**
 *
 * @author aviare
 */
public class SchedulePage extends javax.swing.JFrame implements Runnable {
    ArrayList<JPanel> blockA = new ArrayList();
    ArrayList<JPanel> blockB = new ArrayList();
    ArrayList<JPanel> blockC = new ArrayList();
    ArrayList<JPanel> blockD = new ArrayList();
    /**
     * Creates new form SchedulePage
     * @param name
     */
    public SchedulePage(String name) {
        initComponents();
        
        this.setTitle("SpareLink - "+name);
        
        titleText.setText(name);
        Thread t = new Thread(this);
        t.start();
        
        blockA.add(blockAPanel);
        blockA.add(blockAPanel1);
        blockB.add(blockBPanel);
        blockB.add(blockBPanel1);
        blockC.add(blockCPanel);
        blockC.add(blockCPanel1);
        blockD.add(blockDPanel);
        blockD.add(blockDPanel1);
        writeDayNum();
        setCourses(blockA);
        
    }
    public void writeDayNum(){
        LocalDate currentDate = LocalDate.now();
        int dayOfMonth = currentDate.getDayOfMonth();
        if(dayOfMonth % 2!=0){
            dayText.setText("Day 1");
        } else {
            dayText.setText("Day 2");
        }
    }
    
    public void setCourses(ArrayList<JPanel> block){
        for(JPanel panel : block){  
            for (Component component : panel.getComponents()) {
                if(component instanceof JLabel label) {
                    label.setText("test");
                }
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        returnButton = new javax.swing.JButton();
        titleText = new javax.swing.JLabel();
        timeText = new javax.swing.JLabel();
        dayText = new javax.swing.JLabel();
        blockAPanel = new javax.swing.JPanel();
        className9 = new javax.swing.JLabel();
        classCode9 = new javax.swing.JLabel();
        classTeacher9 = new javax.swing.JLabel();
        classRoomNum9 = new javax.swing.JLabel();
        blockBPanel = new javax.swing.JPanel();
        className1 = new javax.swing.JLabel();
        classCode1 = new javax.swing.JLabel();
        classTeacher1 = new javax.swing.JLabel();
        classRoomNum1 = new javax.swing.JLabel();
        blockCPanel = new javax.swing.JPanel();
        className2 = new javax.swing.JLabel();
        classCode2 = new javax.swing.JLabel();
        classTeacher2 = new javax.swing.JLabel();
        classRoomNum2 = new javax.swing.JLabel();
        blockDPanel = new javax.swing.JPanel();
        className3 = new javax.swing.JLabel();
        classCode3 = new javax.swing.JLabel();
        classTeacher3 = new javax.swing.JLabel();
        classRoomNum3 = new javax.swing.JLabel();
        blockBPanel1 = new javax.swing.JPanel();
        className4 = new javax.swing.JLabel();
        classCode4 = new javax.swing.JLabel();
        classTeacher4 = new javax.swing.JLabel();
        classRoomNum4 = new javax.swing.JLabel();
        blockAPanel1 = new javax.swing.JPanel();
        className5 = new javax.swing.JLabel();
        classCode5 = new javax.swing.JLabel();
        classTeacher5 = new javax.swing.JLabel();
        classRoomNum5 = new javax.swing.JLabel();
        blockDPanel1 = new javax.swing.JPanel();
        className6 = new javax.swing.JLabel();
        classCode6 = new javax.swing.JLabel();
        classTeacher6 = new javax.swing.JLabel();
        classRoomNum6 = new javax.swing.JLabel();
        blockCPanel1 = new javax.swing.JPanel();
        className7 = new javax.swing.JLabel();
        classCode7 = new javax.swing.JLabel();
        classTeacher7 = new javax.swing.JLabel();
        classRoomNum7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        returnButton.setBackground(new java.awt.Color(255, 255, 254));
        returnButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        returnButton.setText("Return");
        returnButton.setBorder(null);
        returnButton.setFocusPainted(false);
        returnButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnButtonActionPerformed(evt);
            }
        });

        titleText.setFont(new java.awt.Font("Helvetica Neue", 0, 36)); // NOI18N
        titleText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleText.setText("STUDENT NAME");

        timeText.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        timeText.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        timeText.setText("00:00 AM");

        dayText.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        dayText.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        dayText.setText("Day X");

        blockAPanel.setBackground(new java.awt.Color(255, 255, 255));
        blockAPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        blockAPanel.setPreferredSize(new java.awt.Dimension(300, 150));

        className9.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        className9.setText("Class Name");

        classCode9.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        classCode9.setText("Class Code");

        classTeacher9.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        classTeacher9.setText("Class Teacher");

        classRoomNum9.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        classRoomNum9.setText("Class Room #");

        javax.swing.GroupLayout blockAPanelLayout = new javax.swing.GroupLayout(blockAPanel);
        blockAPanel.setLayout(blockAPanelLayout);
        blockAPanelLayout.setHorizontalGroup(
            blockAPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(blockAPanelLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(blockAPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(classRoomNum9)
                    .addComponent(classTeacher9)
                    .addComponent(classCode9)
                    .addComponent(className9))
                .addContainerGap(172, Short.MAX_VALUE))
        );
        blockAPanelLayout.setVerticalGroup(
            blockAPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(blockAPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(className9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(classCode9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(classTeacher9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(classRoomNum9)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        blockBPanel.setBackground(new java.awt.Color(255, 255, 255));
        blockBPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        blockBPanel.setPreferredSize(new java.awt.Dimension(300, 150));

        className1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        className1.setText("Class Name");

        classCode1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        classCode1.setText("Class Code");

        classTeacher1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        classTeacher1.setText("Class Teacher");

        classRoomNum1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        classRoomNum1.setText("Class Room #");

        javax.swing.GroupLayout blockBPanelLayout = new javax.swing.GroupLayout(blockBPanel);
        blockBPanel.setLayout(blockBPanelLayout);
        blockBPanelLayout.setHorizontalGroup(
            blockBPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(blockBPanelLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(blockBPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(classRoomNum1)
                    .addComponent(classTeacher1)
                    .addComponent(classCode1)
                    .addComponent(className1))
                .addContainerGap(172, Short.MAX_VALUE))
        );
        blockBPanelLayout.setVerticalGroup(
            blockBPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(blockBPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(className1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(classCode1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(classTeacher1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(classRoomNum1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        blockCPanel.setBackground(new java.awt.Color(255, 255, 255));
        blockCPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        blockCPanel.setPreferredSize(new java.awt.Dimension(300, 150));

        className2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        className2.setText("Class Name");

        classCode2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        classCode2.setText("Class Code");

        classTeacher2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        classTeacher2.setText("Class Teacher");

        classRoomNum2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        classRoomNum2.setText("Class Room #");

        javax.swing.GroupLayout blockCPanelLayout = new javax.swing.GroupLayout(blockCPanel);
        blockCPanel.setLayout(blockCPanelLayout);
        blockCPanelLayout.setHorizontalGroup(
            blockCPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(blockCPanelLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(blockCPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(classRoomNum2)
                    .addComponent(classTeacher2)
                    .addComponent(classCode2)
                    .addComponent(className2))
                .addContainerGap(172, Short.MAX_VALUE))
        );
        blockCPanelLayout.setVerticalGroup(
            blockCPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(blockCPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(className2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(classCode2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(classTeacher2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(classRoomNum2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        blockDPanel.setBackground(new java.awt.Color(255, 255, 255));
        blockDPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        blockDPanel.setPreferredSize(new java.awt.Dimension(300, 150));

        className3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        className3.setText("Class Name");

        classCode3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        classCode3.setText("Class Code");

        classTeacher3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        classTeacher3.setText("Class Teacher");

        classRoomNum3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        classRoomNum3.setText("Class Room #");

        javax.swing.GroupLayout blockDPanelLayout = new javax.swing.GroupLayout(blockDPanel);
        blockDPanel.setLayout(blockDPanelLayout);
        blockDPanelLayout.setHorizontalGroup(
            blockDPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(blockDPanelLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(blockDPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(classRoomNum3)
                    .addComponent(classTeacher3)
                    .addComponent(classCode3)
                    .addComponent(className3))
                .addContainerGap(172, Short.MAX_VALUE))
        );
        blockDPanelLayout.setVerticalGroup(
            blockDPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(blockDPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(className3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(classCode3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(classTeacher3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(classRoomNum3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        blockBPanel1.setBackground(new java.awt.Color(255, 255, 255));
        blockBPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        blockBPanel1.setPreferredSize(new java.awt.Dimension(300, 150));

        className4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        className4.setText("Class Name");

        classCode4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        classCode4.setText("Class Code");

        classTeacher4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        classTeacher4.setText("Class Teacher");

        classRoomNum4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        classRoomNum4.setText("Class Room #");

        javax.swing.GroupLayout blockBPanel1Layout = new javax.swing.GroupLayout(blockBPanel1);
        blockBPanel1.setLayout(blockBPanel1Layout);
        blockBPanel1Layout.setHorizontalGroup(
            blockBPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(blockBPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(blockBPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(classRoomNum4)
                    .addComponent(classTeacher4)
                    .addComponent(classCode4)
                    .addComponent(className4))
                .addContainerGap(172, Short.MAX_VALUE))
        );
        blockBPanel1Layout.setVerticalGroup(
            blockBPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(blockBPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(className4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(classCode4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(classTeacher4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(classRoomNum4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        blockAPanel1.setBackground(new java.awt.Color(255, 255, 255));
        blockAPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        blockAPanel1.setPreferredSize(new java.awt.Dimension(300, 150));

        className5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        className5.setText("Class Name");

        classCode5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        classCode5.setText("Class Code");

        classTeacher5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        classTeacher5.setText("Class Teacher");

        classRoomNum5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        classRoomNum5.setText("Class Room #");

        javax.swing.GroupLayout blockAPanel1Layout = new javax.swing.GroupLayout(blockAPanel1);
        blockAPanel1.setLayout(blockAPanel1Layout);
        blockAPanel1Layout.setHorizontalGroup(
            blockAPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(blockAPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(blockAPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(classRoomNum5)
                    .addComponent(classTeacher5)
                    .addComponent(classCode5)
                    .addComponent(className5))
                .addContainerGap(172, Short.MAX_VALUE))
        );
        blockAPanel1Layout.setVerticalGroup(
            blockAPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(blockAPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(className5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(classCode5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(classTeacher5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(classRoomNum5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        blockDPanel1.setBackground(new java.awt.Color(255, 255, 255));
        blockDPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        blockDPanel1.setPreferredSize(new java.awt.Dimension(300, 150));

        className6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        className6.setText("Class Name");

        classCode6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        classCode6.setText("Class Code");

        classTeacher6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        classTeacher6.setText("Class Teacher");

        classRoomNum6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        classRoomNum6.setText("Class Room #");

        javax.swing.GroupLayout blockDPanel1Layout = new javax.swing.GroupLayout(blockDPanel1);
        blockDPanel1.setLayout(blockDPanel1Layout);
        blockDPanel1Layout.setHorizontalGroup(
            blockDPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(blockDPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(blockDPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(classRoomNum6)
                    .addComponent(classTeacher6)
                    .addComponent(classCode6)
                    .addComponent(className6))
                .addContainerGap(172, Short.MAX_VALUE))
        );
        blockDPanel1Layout.setVerticalGroup(
            blockDPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(blockDPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(className6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(classCode6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(classTeacher6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(classRoomNum6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        blockCPanel1.setBackground(new java.awt.Color(255, 255, 255));
        blockCPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        blockCPanel1.setPreferredSize(new java.awt.Dimension(300, 150));

        className7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        className7.setText("Class Name");

        classCode7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        classCode7.setText("Class Code");

        classTeacher7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        classTeacher7.setText("Class Teacher");

        classRoomNum7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        classRoomNum7.setText("Class Room #");

        javax.swing.GroupLayout blockCPanel1Layout = new javax.swing.GroupLayout(blockCPanel1);
        blockCPanel1.setLayout(blockCPanel1Layout);
        blockCPanel1Layout.setHorizontalGroup(
            blockCPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(blockCPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(blockCPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(classRoomNum7)
                    .addComponent(classTeacher7)
                    .addComponent(classCode7)
                    .addComponent(className7))
                .addContainerGap(172, Short.MAX_VALUE))
        );
        blockCPanel1Layout.setVerticalGroup(
            blockCPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(blockCPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(className7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(classCode7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(classTeacher7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(classRoomNum7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("10:15 - 11:35");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel2.setText("8:55 - 10:10");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel3.setText("12:20 - 1:35");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel4.setText("1:40 - 2:55");

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Logo_Small.png"))); // NOI18N

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setText("Day 2 ");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setText("Day 1 ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(451, 451, 451)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(blockAPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(blockBPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(blockCPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(blockDPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel5)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel4)
                                .addComponent(jLabel3)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(148, 148, 148)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 259, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(blockAPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(blockBPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(blockDPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(blockCPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(434, 434, 434))
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(returnButton, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(titleText)
                        .addGap(697, 697, 697)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(timeText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(dayText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(30, 30, 30))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(559, 559, 559))))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(578, 578, 578)
                    .addComponent(jLabel7)
                    .addContainerGap(1275, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(timeText)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(titleText)
                    .addComponent(dayText))
                .addGap(104, 104, 104)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(blockBPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(blockAPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(blockDPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(blockCPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 123, Short.MAX_VALUE)
                        .addComponent(returnButton, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(blockAPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(60, 60, 60)
                                .addComponent(jLabel2)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(blockBPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(84, 84, 84)
                                .addComponent(jLabel1)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(blockCPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(72, 72, 72)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(blockDPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(49, 49, 49)
                                .addComponent(jLabel4)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5)
                        .addContainerGap())))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(205, 205, 205)
                    .addComponent(jLabel7)
                    .addContainerGap(842, Short.MAX_VALUE)))
        );

        setSize(new java.awt.Dimension(1920, 1080));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void returnButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnButtonActionPerformed
        // TODO add your handling code here:
        close();
        MainMenu menu = new MainMenu();
        menu.setVisible(true);
    }//GEN-LAST:event_returnButtonActionPerformed
    public void close(){
        WindowEvent closeWindow = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(closeWindow);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SchedulePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SchedulePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SchedulePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SchedulePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SchedulePage("").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel blockAPanel;
    private javax.swing.JPanel blockAPanel1;
    private javax.swing.JPanel blockBPanel;
    private javax.swing.JPanel blockBPanel1;
    private javax.swing.JPanel blockCPanel;
    private javax.swing.JPanel blockCPanel1;
    private javax.swing.JPanel blockDPanel;
    private javax.swing.JPanel blockDPanel1;
    private javax.swing.JLabel classCode1;
    private javax.swing.JLabel classCode2;
    private javax.swing.JLabel classCode3;
    private javax.swing.JLabel classCode4;
    private javax.swing.JLabel classCode5;
    private javax.swing.JLabel classCode6;
    private javax.swing.JLabel classCode7;
    private javax.swing.JLabel classCode9;
    private javax.swing.JLabel className1;
    private javax.swing.JLabel className2;
    private javax.swing.JLabel className3;
    private javax.swing.JLabel className4;
    private javax.swing.JLabel className5;
    private javax.swing.JLabel className6;
    private javax.swing.JLabel className7;
    private javax.swing.JLabel className9;
    private javax.swing.JLabel classRoomNum1;
    private javax.swing.JLabel classRoomNum2;
    private javax.swing.JLabel classRoomNum3;
    private javax.swing.JLabel classRoomNum4;
    private javax.swing.JLabel classRoomNum5;
    private javax.swing.JLabel classRoomNum6;
    private javax.swing.JLabel classRoomNum7;
    private javax.swing.JLabel classRoomNum9;
    private javax.swing.JLabel classTeacher1;
    private javax.swing.JLabel classTeacher2;
    private javax.swing.JLabel classTeacher3;
    private javax.swing.JLabel classTeacher4;
    private javax.swing.JLabel classTeacher5;
    private javax.swing.JLabel classTeacher6;
    private javax.swing.JLabel classTeacher7;
    private javax.swing.JLabel classTeacher9;
    private javax.swing.JLabel dayText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JButton returnButton;
    private javax.swing.JLabel timeText;
    private javax.swing.JLabel titleText;
    // End of variables declaration//GEN-END:variables

    @Override
    public void run() {
        while(true){
            LocalTime currentTime = LocalTime.now();
            DateTimeFormatter formatter = DateTimeFormatter.ofPattern("h:mm a", Locale.ENGLISH);
            String formattedTime = currentTime.format(formatter);
            timeText.setText(formattedTime.toUpperCase());
        }
    }
}
